### ISSUE TITLE
[BUG] static libc++ in NDK25 produces external symbols for std::string

### ISSUE THREAD

**Issue by akaStiX** [android/ndk#1731]
### Description

When building Unreal Engine 5 with NDK25 I get
```
std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > std::__ndk1::operator+<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >(char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
```
listed as an undefined symbol and when I try to launch my app I get a runtime linker error
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt6__ndk1plIcNS_11char_traitsIcEENS_9allocatorIcEEEENS_12basic_stringIT_T0_T1_EEPKS6_RKS9_" referenced by "/data/app/com.epicgames.MyProject-nQ4K263jJUd9fnXxlWUnDg==/lib/arm64/libUnreal.so"...
```
We build engine with static libc++, this doesn't happen if I'll switch to libc++_shader.so as it contains implementation for a missing symbol.
This issue isn't happening when building my test app with NDK21 & static libc++.

I inspected libc++_static.a with llvm-nm.exe and it contains 3 entries for operator+ one is marked as weak, while others are marked as undefined.
I compared libc++_static.a from NDK21 & NDK25 and found that in NDK21 there are two instances that are marked as weak and one as undefined.
No idea why linker fails on NDK25

### Affected versions

r25

### Host OS

Windows

### Host OS version

10

### Affected ABIs

arm64-v8a

### Build system

Other (specify below)

### Other build system

Custom Unreal Engine's build system

### minSdkVersion

21

**Comment by akaStiX** [comment]
No. We build libUnreal.so against static libc++. Used to work with NDK21, but now we are planning to move to 25 and I faced this issue. Building against libc++_shared is not an option for us

**Comment by DanAlbert** [comment]
Just checking. On first read I thought you may have been an unreal _user_, rather than building unreal yourself. I had misread though.

If you're building middleware as a shared library, you should follow https://developer.android.com/ndk/guides/middleware-vendors#using_the_stl (specifically the bit about using a version script to make sure you only expose what you intend to expose).

@rprichard is working on upgrading libc++ right now. Until that happens I don't think there's anything we can do with this that wouldn't be a waste of time, since all our custom build configuration (and outdated sources) are being thrown out as a part of that. If the problem still exists after the upgrade, it's most likely an upstream problem.

**Comment by akaStiX** [comment]
Thanks Dan for a quick reply.

I already cleaned up libUnreal.so and it exposes only a handful of symbols that Java needs, everything else is private.
Also I doubt it's related to my issue. Here we rely on external symbol for some reason. To me it seems like there's a problem in libc++_static.a, hence this bug report as I was unable to find a workaround.

Do you have any ETA for libc++ upgrade?
I'd really want to upgrade to NDK25 as 21 has quite outdated toolchain and we had a bunch of issues with it in the past

**Comment by rprichard** [comment]
> I compared libc++_static.a from NDK21 & NDK25 and found that in NDK21 there are two instances that are marked as weak and one as undefined.

When the linker generates libUnreal.so, I suspect it does not include the `operator+` symbol definition from libc++_static.a, because the symbol is exported by a shared object that libUnreal.so depends on. If the library at run-time does not actually export the symbol, then libUnreal.so won't load.

Running `llvm-readelf -d` on libUnreal.so will show the list of DT_NEEDED libraries, and then you could examine those libraries with `llvm-readelf --dyn-syms` to see if any of them export the STL symbol.

Upgrading the libc++ is targeted for NDK r26, to be released sometime in 2023. I wouldn't expect it to fix this problem, though.

**Comment by akaStiX** [comment]
Thanks to Ryan's commentary I was able to find out what was the problem.
libUnreal.so requires libplaycore.so
libplaycore.so exports std::string operator+, the same that libUnreal.so imports.
But for some reason runtime linker failed to resolve this dependency.
I just linked against libplaycore.so built with NDK21 (instead of the one built with NDK23) and it solved my problem.
Good enough solution for me.
Thanks folks for your help!

**Comment by DanAlbert** [comment]
Since you say this was happening on Android 10, where we believe the usual load order bugs that cause such issues are already fixed, if you can upload the artifacts that show the bug we could try to answer why. The easy answer would be that the play more I'm your build is not the same as the one that ends up on the device, but based on your description that doesn't sound like the case.

**Comment by akaStiX** [comment]
It turned out that our build scripts have 2 points of failure instead of one - there is one script that selects which library to link against and a totally different script that copies that lib over to be packaged into an apk.
It turned out that I was linking with NDK23 version of the libplaycore.so, but copying over NDK21 version. That's why operator+ wasn't resolved.
I ended up linking with static lib instead and reported libplaycore.so for re-exporting symbols from static libc++ to our contact person at Google.
Sorry for the trouble. And thanks for your help once again
